version: "3.6"

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    mem_limit: '2g'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data-volume:/data'

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    mem_limit: '2g'
    ports:
      - 27017:27017
    volumes:
      - 'mongodb-data:/data/db'
      - 'mongodb-config:/data/configdb'

volumes:
  redis-data-volume:
    name: redis-data-volume
  mongodb-data:
    name: mongodb-data
  mongodb-config:
    name: mongodb-config
